### ISSUE TITLE
How to enable the h-j-k-l keys for X11 and Cocoa

### ISSUE THREAD

**Issue by Nanoc-ice** [sil-quirk/sil-q#100]
Sil-q version 1.5.0 
I don't have the arrow  keys to work with so I need the alternate h-j-k-l keys to be turned on.  I can see in lib/pref/pref.prf that they are there, but the pref-11.prf and pref-cocoa.prf don't have them and as such are not available to me.  In fact, I would like to turn off the use of numbers and only use the h-j-k-l (and whatever other keys move in diagonal that are associated with them)

**Comment by sil-quirk** [comment]
Have you enabled them using the menu (Options | Interface Options | Move with hjkl)? Or is this disabled on Mac?

**Comment by Nanoc-ice** [comment]
Didnt know it was there until I did the second part of the tutorial.  I have it enabled and works as advertised
