### ISSUE TITLE
"Crowns" missing from Known Artefact object list

### ISSUE THREAD

**Issue by PMantix** [sil-quirk/sil-q#11]
In 1.4.2, I noticed the "Known Artefacts" list was incorrectly showing crowns under the "boots" group, and boots under the "Chests" group.

I dug into the source and found that the issue. The object_group_text list defined in src/cmd4.c was **_missing the "Crowns" entry_** between "Helms" and "Boots". This entry is present in all previous versions of Sil-Q, so not sure what happened there? 

Anyway, the revised code is shown below (which I compiled and tested) for your reference (Sorry, I'm new to this...  Would have been better to make a pull request, right? Anyway, it's a one line fix.)

(within src/cmd4.c)

static cptr object_group_text[] =
{
	"Herbs",
	"Potions",
	"Rings",
	"Amulets",
	"Staves",
	"Horns",
	"Swords",
	"Axes & Polearms",
	"Blunt Weapons",
	"Diggers",
	"Bows",
//	"Arrows",
	"Light Sources",
	"Soft Armour",
	"Mail",
	"Shields",
	"Cloaks",
	"Gloves",
	"Helms",
	"Crowns",   // <---This line needs to be added back in! :-)
	"Boots",
	"Chests",
	NULL
};

**Comment by Peter-CYF** [comment]
Have re-added it. Looks like the error came when I was removing crowns from smithing, I must have thought the list applied to smithing in some context, but having been back through the code and also tested smithing, clearly this is not the case. Fix looks safe. Please confirm the new commit works for you and I'll close the issue.

**Comment by sil-quirk** [comment]
Have re-added it. Looks like the error came when I was removing crowns from smithing, I must have thought the list applied to smithing in some context, but having been back through the code and also tested smithing, clearly this is not the case. Fix looks safe. Please confirm the new commit works for you and I'll close the issue.

**Comment by PMantix** [comment]
Confirmed, crowns now show up as "crowns", and boots now show up as "boots". 👍

**Comment by sil-quirk** [comment]
Great. Thanks for catching this and supplying the fix.
