### ISSUE TITLE
Tutorial references (and requires) wrong songs

### ISSUE THREAD

**Issue by slitherrr** [sil-quirk/sil-q#12]
The tutorial notes reference the Song of Trees and the Song of Slaying, but the songs available to the character are Challenge and Silence, which aren't particularly useful in either of the song tutorial rooms.

**Comment by Peter-CYF** [comment]
Can you confirm the version here? This bug is present in the most recent release, but the current dev version should have fixed it as of commit https://github.com/sil-quirk/sil-q/commit/0af27fea64b31c9c5ec7277ddb3b63793fb14c4e.

**Comment by sil-quirk** [comment]
Can you confirm the version here? This bug is present in the most recent release, but the current dev version should have fixed it as of commit 0af27fe.

**Comment by slitherrr** [comment]
Ah, sorry, this is from the most recent release, I should have thought to check mainline.
