### ISSUE TITLE
Text is garbled

### ISSUE THREAD

**Issue by Chaoclypse** [sil-quirk/sil-q#13]
Hello!

I compiled Sil-Q on a Ubuntu terminal (which I am accessing via SSH), but the text is garbled when I compile using GCU.

As an example, when I press Escape and Escape again to get out of the menu, I get this:

![Termius_09-03-2020_21-09-32](https://user-images.githubusercontent.com/13073480/76215712-48667e80-624a-11ea-9a24-7e396f45df86.png)

I suspect that the garbled text is due to the screen not being cleared properly, but I could be completely wrong!

**Comment by sil-quirk** [comment]
Hi, this is likely to be an interaction with SSH (I know of no reports of this happening locally). What are you using to SSH in - another Linux terminal, PuTTY, something else?

**Comment by Chaoclypse** [comment]
I thought it may be that as well, but I actually tested it on both Blink (iOS SSH app) and Termius (Windows SSH Program) with the exact same results.

**Comment by sil-quirk** [comment]
I suspect this will be a case of massaging your SSH terminal settings. I note Termius has a history of similar issues with other applications e.g. https://github.com/Eugeny/terminus/issues/28, https://github.com/Eugeny/terminus/issues/729. One thing that some noted to work in those other cases was switching to `hterm` or `xterm (WebGL)` so I'd suggest trying that, but in general I don't explicitly attempt to provide support for accessing the terminal via SSH.

**Comment by Chaoclypse** [comment]
@sil-quirk I'm not using terminus, I'm using termius, but that link really helped! I was able to get the error to stop happening by setting TERM to linux. 

I'm not sure if I should open up another issue for this, so I thought I'd address it here - when I press escape, it takes a while to process the command. This does not happen for any other key, as far as I can tell. Has this been reported and if so, is there any way to remedy this? Thanks so much!

**Comment by sil-quirk** [comment]
Ah, I must have typoed, my bad. Glad it helped anyway.

I haven't come across any issues reported with the escape key and have no issues running locally, so this may also be a thing requiring some SSH setting massage.

**Comment by Chaoclypse** [comment]
@sil-quirk I looked in the source files and noticed that the back-tick (`) was mapped to escape, so I tried that and it didn't have any delay at all! I guess I'll be using that for the time being! :)

One final question (I think), is there any way to disable the cursor? It's a bit distracting being on the screen all the time. Is this also possibly a by-product of the SSH settings?

**Comment by sil-quirk** [comment]
The cursor is a likely unavoidable artefact of using ncurses I think, it is there blinking away on the bottom right in local GCU also.

**Comment by Chaoclypse** [comment]
Thanks for the clarification! And for the quick replies! I can't wait to play the game, heard so many good things about it :)
