### ISSUE TITLE
One more step required for Linux installation

### ISSUE THREAD

**Issue by umazanatastatura** [sil-quirk/sil-q#51]
When running command (step 3) Go back to the Sil folder and start Sil-Q with "sil", error happens (maybe it's just me but):

./sil: Cannot create the './lib/apex/scores.raw' file!

I checked permissions on my folders and they are all there so... after that error I just created apex folder and in it empty "scores.raw" file and it worked.
Idk if it should be mentioned as additional info on installation step 3

**Comment by sil-quirk** [comment]
Hi, could you give a little more information on this? I cannot replicate this; if I clone clean and build, it creates scores.raw without trouble when I run ./sil, and if I delete scores.raw and run ./sil again it recreates it.

Did you git clone or download a zip of the code?

**Comment by umazanatastatura** [comment]
Just tried with git clone and then making executable and it works without error! First time I downloaded zip of the code and that is the case when it refuses to create scores.raw
