### ISSUE TITLE
Linux: if tiles are resampled, alert indicator may be opaque

### ISSUE THREAD

**Issue by backwardsEric** [sil-quirk/sil-q#52]
Compiling with the default Makefile.std on Debian Buster and running with ./sil -mx11 -- -g , I see that once a creature becomes alert the rendering of the alert indicator obscures the creature's tile.  Checking under the debugger, the tiles were being resampled to 10 x 20 from 16 x 16 to match the font that was used.

**Comment by sil-quirk** [comment]
Reproduced. Thanks for fixing this. Perils of testing with ./silg all the time.
