### ISSUE TITLE
1.5.0 beta2 - inv/equip windows issue

### ISSUE THREAD

**Issue by davidk64fnq** [sil-quirk/sil-q#62]
Using Windows 10 Pro the inventory and equipment windows with tiles. The column to the right of the icons is duplicated once.

Edit: quitting and reloading Sil-Q fixes the problem.
Edit2: it happens when you go from no tiles to tiles.

**Comment by sil-quirk** [comment]
Thanks for bringing this to my attention, I'll look into it.

**Comment by backwardsEric** [comment]
I suspect that the problem was fixed by https://github.com/sil-quirk/sil-q/pull/28 .  That change happened after 1.5.0 beta2.
