### ISSUE TITLE
1.5.0 beta2 - main screen searching

### ISSUE THREAD

**Issue by davidk64fnq** [sil-quirk/sil-q#63]
Using Windows 10 Pro with the tileset. When in searching mode there is no text at bottom of window to show I'm in searching mode. Although I can see the +5 in character window.

**Comment by sil-quirk** [comment]
Despite an errant line in the old manual, there is no search mode in Sil. I am curious what you mean by "I can see the +5 in the character window".

**Comment by davidk64fnq** [comment]
Sorry I see it is called Stealth mode. So +5 on the stealth line.  Further testing just now showed the issue was too large a font setting resulting in that display text not being visible. Thanks
