### ISSUE TITLE
1.5.0 beta2 - diagonal running?

### ISSUE THREAD

**Issue by davidk64fnq** [sil-quirk/sil-q#64]
Using Windows 10 Pro. Shift + 1/3/7/9 doesn't give running in those directions.

**Comment by Peter-CYF** [comment]
Have tested and this appears to work with the appropriate numpad keys - shift-PgDn, PgUp, Home and End.

With the number keys above the alphabet keys this does not work and should not be expected to work; those submit non-alphanumeric characters such as ! and & on entry and & in particular is bound to the colour modification menu.

On keyboards without numpads where PgDn, PgUp etc may be awkward, vi keys are recommended.

**Comment by sil-quirk** [comment]
Have tested and this appears to work with the appropriate numpad keys - shift-PgDn, PgUp, Home and End.

With the number keys above the alphabet keys this does not work and should not be expected to work; those submit non-alphanumeric characters such as ! and & on entry and & in particular is bound to the colour modification menu.

On keyboards without numpads where PgDn, PgUp etc may be awkward, vi keys are recommended.

**Comment by davidk64fnq** [comment]
I had another look after reading your reply. I had NumLock turned on. Once I turned it off it worked fine. Sorry about that!
