### ISSUE TITLE
Feature request - ability to scroll and select highlighted item in list

### ISSUE THREAD

**Issue by davidk64fnq** [sil-quirk/sil-q#66]
Say I type "u" to use a weapon and then "/" if I need to toggle between equipment and inventory list, then to confirm use of a particular item in the displayed list I type the corresponding letter. Would it be possible to provide capability to change the selected item in the list using the up/down arrow keys and then enter to confirm selected item?

Reason for asking is to facilitate playing Sil-Q with a controller. Apart from selecting items from a list the number of keys used is relatively small. But if you need to type the letter of a selected item from a list it increases significantly.

If this is doable but involves lots of work then I'm sure it's not worth it for the small number of users who would want to play Sil-Q using a controller.

Note: for anybody reading Keysticks.net is a great controller mapping software with lots of features that I haven't seen elsewhere.

![keysticks-net](https://user-images.githubusercontent.com/63939880/107441989-f6c52300-6b81-11eb-997b-be455cbf9d3d.jpg)

Edit: Right/left trigger navigates to a 2nd and 3rd action strip (the thing on the right), I have one with uppercase and one with non-character keys

**Comment by sil-quirk** [comment]
I'm afraid it would be quite a bit of work to implement this - it would require quite an overhaul of the very archaic menu code. I'll consider it for the future but it's unlikely to make it into the next release.

**Comment by davidk64fnq** [comment]
Given it's a lot of work I believe it's not worth it. The effort is better spent in other areas.
