### ISSUE TITLE
1.5.0 beta2 - stealth issue?

### ISSUE THREAD

**Issue by davidk64fnq** [sil-quirk/sil-q#68]
Regarding "If you passed last turn (pressed (5) or (z), or (Z)), you get a bonus of +7 to your stealth (not cumulative with Stealth mode)." in Sil 1.3 manual - is this supposed to still apply? I've tried expecting to see a +7 appear in character display but it doesn't. Is this factor only calculated internally unlike stealth mode?

**Comment by sil-quirk** [comment]
This applies but you will not see it in the character window as it will not apply to your next action (unless that action is resting).
