### ISSUE TITLE
s32b/u32b end up as 64-bit types by default on macOS and 64-bit Linux

### ISSUE THREAD

**Issue by backwardsEric** [sil-quirk/sil-q#78]
I'm guessing that this is already known, but, in case it isn't, the standard compilation procedures on macOS and 64-bit Linux generate code that uses 64-bit integers for s32b and u32b.

Modifying h-config.h so L64 is set for those systems would fix that (and presumably make it easier to transfer savefiles between macOS or 64-bit Linux and Windows or 32-bit Linux) but break backwards compatibility with savefiles previously generated on macOS or 64-bit Linux.

**Comment by sil-quirk** [comment]
Fixed using uint32_t, int32_t - should work across the board.
