### ISSUE TITLE
Vow of Iron broken by chest trap

### ISSUE THREAD

**Issue by svalbardcaretaker** [sil-quirk/sil-q#86]
Greetings, Vow of Iron on Edain in the attached safefile. After opening a trapped chest I got bad poisoning and somehow the bonus of Vow of Iron got lost - it still shows active in the skills. I will play a bit more to see if it re-establishes. 
[Aronel.zip](https://github.com/sil-quirk/sil-q/files/7100317/Aronel.zip)

PS. thanks for update, looking forward to playing it!

**Comment by sil-quirk** [comment]
Thanks very much for posting this. I have had several reports of this nature, and have yet to get to the bottom of it. The savefile may make this a great deal easier.

**Comment by sil-quirk** [comment]
Interesting and alarming: the savefile has the right behaviour on Linux, where I usually develop, but wrong on Windows. Digging deeper.

**Comment by sil-quirk** [comment]
Your savefile ended up leading me to the bug. Thank you very much. That would have been very difficult to track down without a savefile. If you want to keep the savefile, there should be a release containing this fix in the next week or two that should restore Aronel's constitution.

**Comment by svalbardcaretaker** [comment]
Glad to hear it. I'll leave feedback on the other changes in the aangband forums.
