### ISSUE TITLE
Permanently Slowed

### ISSUE THREAD

**Issue by ElijahRSmith** [sil-quirk/sil-q#93]
Picking up a Wooden Torch (557 turns) gave me a slow debuff that has persisted indefinitely. Drinking a potion of quickness temporarily returned my speed to normal, but after its effects ended, the debuff returned. Is this a bug or am I missing something obvious?

I am using sil-q v1.5.0 on a windows machine.

**Comment by sil-quirk** [comment]
Double-check that you are not carrying more weight than your strength allows (this should be visible from the character screen).

If this is not the case, it would be useful to have an uploaded savefile.

**Comment by ElijahRSmith** [comment]
It was just the carrying capacity after all. I was afraid my problem might be something obvious. Sorry about that. Thank you for your help!
